apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    env: dev
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        env: dev
        app: nginx
    spec:
      containers:
        - image: nginx:1.14.2
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
          resources: { }
