apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    env: dev
    app: django
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 100
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 200
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: juneshone/django_app:latest
            imagePullPolicy: IfNotPresent
            command: ["python", "manage.py", "clearsessions"]
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: url
            envFrom:
              - secretRef:
                  name: secrets
          restartPolicy: OnFailure