apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    env: dev
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: django
  template:
    metadata:
      name: django
      labels:
        env: dev
        app: django
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: pg-root-cert
            defaultMode: 384
      containers:
        - env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secret_key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: url
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: allowed_hosts
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: debug
          image: juneshone/django_app:latest
          imagePullPolicy: IfNotPresent
          name: django
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "~/.postgresql"
          ports:
            - containerPort: 80
          resources: { }