apiVersion: batch/v1
kind: Job
metadata:
  name: job-migrate
  labels:
    env: dev
    app: django
spec:
  ttlSecondsAfterFinished: 200
  template:
    spec:
      containers:
      - name: job-migrate
        image: juneshone/django_app:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py", "migrate", "--noinput"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: url
        envFrom:
          - secretRef:
              name: secrets
      restartPolicy: Never
  backoffLimit: 4