apiVersion: batch/v1
kind: Job
metadata:
  name: job-migrate
  labels:
    env: dev
    app: django
spec:
  ttlSecondsAfterFinished: 200
  template:
    spec:
      containers:
      - name: job-migrate
        image: django_app:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py", "migrate", "--noinput"]
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: secret_key
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: secrets
                key: database_url
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: secrets
                key: allowed_hosts
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: secrets
                key: debug
      restartPolicy: Never
  backoffLimit: 4